apiVersion: v1
kind: Service
metadata:
  name: {{ include "dmm-torznab.fullname" . }}
  labels:
    {{- include "dmm-torznab.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dmm-torznab.selectorLabels" . | nindent 4 }}
